import {AIVoiceInput} from '@/components/ui/ai-voice-input'
import {ExpandableChatDemo} from '@/components/sidechatbot'
import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@/lib/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <UserProvider>
          {children}
        </UserProvider>
        <div className="fixed top-2 right-5 z-50">
          <AIVoiceInput />
        </div>
        <div className="fixed bottom-2 right-5 z-50">
          <ExpandableChatDemo />
        </div>
      </body>
    </html>
  )
}
